require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'PlanoDePartoSimples' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  target 'PlanoDePartoSimplesTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(installer)
  end
end